package report

import (
	"encoding/json"
	"fmt"
	"runtime"
	"strings"
	"time"

	"github.com/ivysterling59-cyber/compatprobe/internal/core"
	"github.com/ivysterling59-cyber/compatprobe/internal/redact"
)

const SchemaVersion = "1"

type Metadata struct {
	Version     string    `json:"version"`
	GeneratedAt time.Time `json:"generated_at"`
}
type Target struct {
	BaseURL string `json:"base_url"`
	Model   string `json:"model"`
}
type Environment struct {
	OS           string `json:"os"`
	Architecture string `json:"architecture"`
	GoVersion    string `json:"go_version"`
}
type Report struct {
	SchemaVersion string               `json:"schema_version"`
	Metadata      Metadata             `json:"metadata"`
	Target        Target               `json:"target"`
	Environment   Environment          `json:"environment"`
	Timeline      []core.TimelineEvent `json:"timeline"`
	Probes        []core.ProbeResult   `json:"probes"`
	Diagnoses     []core.Diagnosis     `json:"diagnoses"`
	CheckTimeout  time.Duration        `json:"-"`
	secrets       []string
}

func New(version, baseURL, model string, timeline []core.TimelineEvent, probes []core.ProbeResult, diagnoses []core.Diagnosis, secrets ...string) Report {
	if timeline == nil {
		timeline = []core.TimelineEvent{}
	}
	if probes == nil {
		probes = []core.ProbeResult{}
	}
	if diagnoses == nil {
		diagnoses = []core.Diagnosis{}
	}
	return Report{SchemaVersion: SchemaVersion, Metadata: Metadata{Version: version, GeneratedAt: time.Now().UTC()}, Target: Target{BaseURL: redact.URL(baseURL), Model: redact.String(model)}, Environment: Environment{OS: runtime.GOOS, Architecture: runtime.GOARCH, GoVersion: runtime.Version()}, Timeline: timeline, Probes: probes, Diagnoses: diagnoses, secrets: secrets}
}

func JSON(r Report) ([]byte, error) {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return nil, err
	}
	out := redact.Secrets(string(b), r.secrets...)
	for _, secret := range r.secrets {
		if secret == "" {
			continue
		}
		encoded, _ := json.Marshal(secret)
		if len(encoded) >= 2 {
			out = strings.ReplaceAll(out, string(encoded[1:len(encoded)-1]), redact.Replacement)
		}
	}
	return []byte(out + "\n"), nil
}

func Markdown(r Report) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# CompatProbe Report\n\nGenerated by CompatProbe %s at %s.\n\n", r.Metadata.Version, r.Metadata.GeneratedAt.Format(time.RFC3339))
	fmt.Fprintf(&b, "## Target\n\n- Endpoint: `%s`\n- Model: `%s`\n- Environment: `%s/%s` (%s)\n", r.Target.BaseURL, r.Target.Model, r.Environment.OS, r.Environment.Architecture, r.Environment.GoVersion)
	if r.CheckTimeout > 0 {
		fmt.Fprintf(&b, "- Overall check timeout: `%s` (shared by all probes)\n", r.CheckTimeout)
	}
	b.WriteByte('\n')
	b.WriteString("## Probe summary\n\n| Probe | Status | Duration |\n|---|---:|---:|\n")
	for _, p := range r.Probes {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", p.Name, p.Status, formatDuration(p.Duration))
	}
	b.WriteString("\n## Probe errors\n\n")
	hasErrors := false
	for _, p := range r.Probes {
		if p.Error != nil {
			hasErrors = true
			fmt.Fprintf(&b, "- `%s` (`%s`): %s\n", p.Name, p.Error.Kind, p.Error.Message)
		}
	}
	if !hasErrors {
		b.WriteString("None.\n")
	}
	if stream := probeByName(r.Probes, "stream_completion"); stream != nil {
		framing := probeByName(r.Probes, "sse_framing")
		finish := probeByName(r.Probes, "finish_semantics")
		b.WriteString("\n## Streaming observations\n\n")
		markdownFact(&b, "Requested `max_completion_tokens` budget", stream, "requested_max_completion_tokens", "")
		markdownFact(&b, "HTTP status", stream, "http_status", "")
		markdownFact(&b, "Content-Type", stream, "content_type", "")
		markdownFact(&b, "Actual observed stream duration", stream, "stream_duration_ms", " ms")
		markdownFact(&b, "Observed SSE events/chunks", stream, "chunks", "")
		markdownFact(&b, "Valid SSE frames", framing, "valid_sse_frames", "")
		markdownFact(&b, "Invalid SSE frames", framing, "invalid_sse_frames", "")
		markdownFact(&b, "finish_reason seen", finish, "finish_reason_seen", "")
		markdownFact(&b, "[DONE] seen", finish, "done_seen", "")
		markdownFact(&b, "Clean EOF", stream, "clean_eof", "")
		markdownFact(&b, "Transport error", stream, "transport_error", "")
		b.WriteString("\nThis completion-token budget can include visible output and reasoning tokens; it does not guarantee a visible-token count or imply a stream duration.\n")
	}
	b.WriteString("\n## Timeline\n\n```text\n")
	for _, e := range r.Timeline {
		fmt.Fprintf(&b, "%-10s %s", formatDuration(e.Timestamp), e.Name)
		if len(e.Metadata) > 0 {
			fmt.Fprintf(&b, " %v", e.Metadata)
		}
		b.WriteByte('\n')
	}
	b.WriteString("```\n\n")
	b.WriteString("## Diagnosis\n\n")
	if len(r.Diagnoses) == 0 {
		b.WriteString("No high-confidence compatibility failure was diagnosed.\n\n")
	}
	for _, d := range r.Diagnoses {
		fmt.Fprintf(&b, "### %s - %s confidence\n\n%s\n\nEvidence:\n\n", d.Code, d.Confidence, d.Summary)
		for _, e := range d.Evidence {
			fmt.Fprintf(&b, "- %s\n", e)
		}
		b.WriteString("\nSuggestions:\n\n")
		for _, s := range d.Suggestions {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteByte('\n')
	}
	b.WriteString("## Minimal reproduction\n\nSupply credentials through `COMPATPROBE_API_KEY`; credentials are intentionally omitted from this report. Reapply any required custom headers privately.\n\n")
	shell := "sh"
	if r.Environment.OS == "windows" {
		shell = "powershell"
	}
	fmt.Fprintf(&b, "```%s\ncompatprobe check --base-url %s --model %s", shell, reproductionArg(redact.Secrets(r.Target.BaseURL, r.secrets...), shell), reproductionArg(redact.Secrets(r.Target.Model, r.secrets...), shell))
	if stream := probeByName(r.Probes, "stream_completion"); stream != nil {
		if budget, ok := stream.Facts["requested_max_completion_tokens"]; ok {
			fmt.Fprintf(&b, " --stream-tokens %v", budget)
		}
	}
	if r.CheckTimeout > 0 {
		fmt.Fprintf(&b, " --timeout %s", r.CheckTimeout)
	}
	b.WriteString("\n```\n")
	return []byte(redact.Secrets(b.String(), r.secrets...))
}

func markdownFact(b *strings.Builder, label string, probe *core.ProbeResult, key, unit string) {
	if probe != nil {
		if value, ok := probe.Facts[key]; ok && value != nil {
			if text, ok := value.(string); ok && text == "" {
				value = "none"
			}
			fmt.Fprintf(b, "- %s: `%v%s`\n", label, value, unit)
			return
		}
	}
	fmt.Fprintf(b, "- %s: not observed\n", label)
}

func reproductionArg(value, shell string) string {
	if shell == "powershell" {
		return "'" + strings.ReplaceAll(value, "'", "''") + "'"
	}
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func Terminal(r Report) []byte {
	var b strings.Builder
	b.WriteString("CompatProbe\n\nTarget\n----------------------------------\n")
	fmt.Fprintf(&b, "Endpoint  %s\nModel     %s\n\nProbes\n----------------------------------\n", r.Target.BaseURL, r.Target.Model)
	for _, p := range r.Probes {
		fmt.Fprintf(&b, "%-32s %-5s %s\n", p.Name, p.Status, formatDuration(p.Duration))
		if p.Error != nil {
			fmt.Fprintf(&b, "  %s: %s\n", p.Error.Kind, p.Error.Message)
		}
	}
	if stream := probeByName(r.Probes, "stream_completion"); stream != nil {
		framing := probeByName(r.Probes, "sse_framing")
		finish := probeByName(r.Probes, "finish_semantics")
		b.WriteString("\nStreaming\n----------------------------------\n")
		fmt.Fprintf(&b, "Requested max_completion_tokens budget %v\n", stream.Facts["requested_max_completion_tokens"])
		fmt.Fprintf(&b, "Observed duration      %v ms\n", stream.Facts["stream_duration_ms"])
		fmt.Fprintf(&b, "Content-Type          %v\n", stream.Facts["content_type"])
		if framing != nil {
			fmt.Fprintf(&b, "Valid SSE frames      %v\n", framing.Facts["valid_sse_frames"])
			fmt.Fprintf(&b, "Invalid SSE frames    %v\n", framing.Facts["invalid_sse_frames"])
		}
		if finish != nil {
			fmt.Fprintf(&b, "finish_reason seen    %v\n", finish.Facts["finish_reason_seen"])
			fmt.Fprintf(&b, "[DONE] seen           %v\n", finish.Facts["done_seen"])
		}
	}
	b.WriteString("\nDiagnosis\n----------------------------------\n")
	if len(r.Diagnoses) == 0 {
		b.WriteString("No high-confidence compatibility failure diagnosed.\n")
	}
	for _, d := range r.Diagnoses {
		fmt.Fprintf(&b, "%s  %s\n%s\n", d.Confidence, d.Code, d.Summary)
	}
	return []byte(redact.Secrets(b.String(), r.secrets...))
}

func probeByName(probes []core.ProbeResult, name string) *core.ProbeResult {
	for i := range probes {
		if probes[i].Name == name {
			return &probes[i]
		}
	}
	return nil
}

func formatDuration(d time.Duration) string {
	if d < time.Millisecond {
		return fmt.Sprintf("%.1f ms", float64(d)/float64(time.Millisecond))
	}
	if d < time.Second {
		return fmt.Sprintf("%d ms", d.Milliseconds())
	}
	return fmt.Sprintf("%.2f s", d.Seconds())
}
